name: Notify Main Project

on: push

jobs:
  notify-main-project:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: jhh977/Travel-Agency-Frontend@v1
      with:
        token: ${{ secrets.PAT }}
        repository: jhh977/Travel-Agency-Frontend
        event-type: update-submodules-event
